[package]
name = "Web-Service"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
dotenvy = "0.15.7"
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
diesel = { version = "2.3.13", features = ["mysql", "r2d2", "chrono"] }
bcrypt = "0.19.3"
jsonwebtoken = "11.0.0"